#!/usr/bin/env python3


#Different Coding Schemes of +CME ERROR: <err>
CME_ERROR = { 
0: "Phone failure",
1: "No connection to phone",
2: "Phone-adaptor link reserved",
3: "Operation not allowed",
4: "Operation not supported",
5: "PH-SIM PIN required",
6: "PH-FSIM PIN required",
7: "PH-FSIM PUK required",
10: "(U)SIM not inserted",
11: "(U)SIM PIN required",
12: "(U)SIM PUK required",
13: "(U)SIM failure",
14: "(U)SIM busy",
15: "(U)SIM wrong",
16: "Incorrect password",
17: "(U)SIM PIN2 required",
18: "(U)SIM PUK2 required",
20: "Memory full",
21: "Invalid index",
22: "Not found",
23: "Memory failure",
24: "Text string too long",
25: "Invalid characters in text string",
26: "Dial string too long",
27: "Invalid characters in dial string",
30: "No network service",
31: "Network timeout",
32: "Network not allowed - emergency calls only",
40: "Network personalization PIN required",
41: "Network personalization PUK required",
42: "Network subset personalization PIN required",
43: "Network subset personalization PUK required",
44: "Service provider personalization PIN required",
45: "Service provider personalization PUK required",
46: "Corporate personalization PIN required",
47: "Corporate personalization PUK required",
300: "ME failure",
301: "SMS ME reserved",
302: "Operation not allowed",
303: "Operation not supported",
304: "Invalid PDU mode",
305: "Invalid text mode",
310: "(U)SIM not inserted",
311: "(U)SIM pin necessary",
312: "PH (U)SIM pin necessary",
313: "(U)SIM failure",
314: "(U)SIM busy",
315: "(U)SIM wrong",
316: "(U)SIM PUK required",
317: "(U)SIM PIN2 required",
318: "(U)SIM PUK2 required",
320: "Memory failure",
321: "Invalid memory index",
322: "Memory full",
330: "SMSC address unknown",
331: "No network",
332: "Network timeout",
500: "Unknown",
512: "(U)SIM not ready",
513: "Message length exceeds",
514: "Invalid request parameters",
515: "ME storage failure",
517: "Invalid service mode",
528: "More message to send state error",
529: "MO SMS is not allow",
530: "GPRS is suspended",
531: "ME storage full" }

#print(CME_ERROR)